kind: pipeline
name: default

steps:
    - name: build
      image: golang
      commands:
          - cd backend
          - go build
    - name: lint
      image: golangci/golangci-lint:v1.40-alpine
      commands:
          - cd backend
          - golangci-lint run

