version: '3.7'

services:
  web:
    build: .
    command: gunicorn -w 3 run:app -b 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
    ports:
      - 8004:8000
    env_file:
      - ./.env.dev
    restart: always
  db:
    image: postgres:11
    volumes:
      - /home/ente/docker/volumes/homework_db:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
